#ifndef ERROS_H
#define ERROS_H

#define ERRO_ARG_INVALIDO 1
#define ERRO_ALOC_MEMORIA 2
#define ERRO_NOME_ARQ_NULL 3
#define ERRO_ABRIR_ARQUIVO 4
#define ERRO_LER_ARQUIVO 5
#define ERRO_CRIAR_ARQUIVO 6
#define ERRO_ESCREVER_ARQUIVO 7

#endif // ERROS_H
