#ifndef GAUSS_JACOBI_H
#define GAUSS_JACOBI_H

#define GAUSS_JACOBI_ERRO_DIM_INCOMP 30
#define GAUSS_JACOBI_ERRO_ALOC_MEM 31
#define GAUSS_JACOBI_ERRO_INI_THREAD 32
#define GAUSS_JACOBI_ERRO_AGU_EXE_THREAD 33

void gauss_jacobi();

#endif // GAUSS_JACOBI_H
